### ISSUE TITLE
DoubletFinder function names have changed [bug]

### ISSUE THREAD

**Issue by CharlotteAnne** [combiz/scFlow#199]
DoubletFinder has been updated in November 2023:
"(11/21/2023) Made compatible with Seurat v5 and removed '_v3' flag from relevant function names."

Because they do no version control - there are no releases in the DoubletFinder github it's not as easy as just installing a previous version of DoubletFinder to avoid this, I would suggest updating the scFlow code to remove _v3 flag from DoubletFinder functions, or else it can't be installed.

**Comment by nfancy** [comment]
resolved at https://github.com/combiz/scFlow/pull/200
